### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by ebekebe** [moll/js-ddl#2]
The example from the [docs](https://github.com/moll/js-ddl/blob/master/doc/API.md#ddlpostgresqlconnection-tablename-callback-) doesn't work for me:

```
var Ddl = require("ddl")
var Pg = require("pg")

var db = new Pg.Client("postgresql://localhost/world")
db.connect()

Ddl.postgresql(db, "people", console.log)
```

I don't get an error, but just `null Ddl {}`. Since there is no error message, I can't get it to return anything useful.

I use the docker image from https://hub.docker.com/r/library/postgres/.

**Comment by moll** [comment]
Hey! The table on which you're running `Ddl.postgresql` extsts beforehand and has columns, right?

**Comment by ebekebe** [comment]
Sorry, for the delay. Yes, the table exists beforehand and has columns. So the output should not be empty. Anyway, even if I try it on a non-existing table the function succeeds with `null Ddl {}`.

**Comment by moll** [comment]
Would you mind helping debug this if it's still a prob? Ddl.js is internally fairly easy. It first fires off a SQL query to get the columns and then maps them a little for JSON Schema use. Would you mind trying to run https://github.com/moll/js-ddl/blob/master/lib/postgresql.sql yourself (replace the `$1` in the code with your own table name and seeing what that returns? Thanks!

**Comment by moll** [comment]
I'll close this as I assume all went well. If it didn't, let me know.
