### ISSUE TITLE
Timestamp columns show up as string

### ISSUE THREAD

**Issue by vurankar** [moll/js-ddl#3]
Hi, 

I am trying to get the schema of a postgresql table. The timestamp columns show up as String. 
I see that this is kind of deliberate from [postgresql.js](https://github.com/moll/js-ddl/blob/462809899e39c806c593056018b5ac24c0103666/lib/postgresql.js#L78). Is there any reason for this ?  will you accept a PR to fix this ?

Thanks

**Comment by moll** [comment]
Hi!

What would you recommend they show up as?

**Comment by vurankar** [comment]
They should show up as timestamp, timestamptz and date  respectively depending on the column type.

**Comment by moll** [comment]
Ah. Well, Ddl.js really just converts the schema to a JSON Schema compatible format and JSON Schema lacks such time types. I myself did need the original type as well, so I think I added a non-enumerable key in that returned object with the original type. I could in some way standardize that, but if you use that somewhat-internal key for now, would it solve your use case?

**Comment by vurankar** [comment]
Thanks for the information, let me check if that works. I will get back.

**Comment by vurankar** [comment]
with the current information returned I could not distinguish between string, date and timestamp column types. I have raised a PR to return date and timestamp differently. 
This fixes my use case. If you think it is acceptable please merge the PR.

**Comment by moll** [comment]
Hey, thanks for the PR, but I unfortunately can't incorporate it in its current form as the JSON Schema standard doesn't support date types. If it wasn't clear what I meant by JSON Schema, then these links may shine some light: http://json-schema.org/specification.html and https://spacetelescope.github.io/understanding-json-schema/.

My proposed temporary workaroudn for you was https://github.com/moll/js-ddl/blob/462809899e39c806c593056018b5ac24c0103666/lib/postgresql.js#L51-L54. Did you look at that?

**Comment by vurankar** [comment]
Got it. Thanks for adding the _type attribute. I will convert the types accordingly in the consumer method.
